schema_version = "1.0.0"

id = "Marcels_Utilities"
version = "1.0.0"
name = "Marcels Utilities"
tagline = "Collection of Blender Utilities"
maintainer = "Marcel Graf <graf.marcel@gmx.net>"
type = "add-on"

tags = ["Utility"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

copyright = ["2025 Marcel Graf"]

tracker_url = "https://github.com/magrf/Marcels_Utilities"

[permissions]
files = "Access to files within the add-on zip structure"
