schema_version = "1.0.0"

id = "metads_screen_presets"
version = "1.0.0"
name = "met[ads] Screen Presets"
tagline = "Streamlined Set-Up for OOH Screens by met[ads]"
maintainer = "Marcel Graf <marcel@met-ads.com>"
type = "add-on"

tags = ["Screen Setup", "Preset"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

copyright = ["2025 Marcel Graf", "2025 met[ads]"]

tracker_url = "https://github.com/marcelmetads/met-ads-Screen-Presets"

[permissions]
files = "Access to files within the add-on zip structure"
